import type { Metadata } from "next";
import { NotificationProvider } from "@/hooks/providerAlert";
import "./globals.css";
import SmoothScroll from "./components/smoothScroll";



export const metadata: Metadata = {
  title: "отзывы и предложения",
  description: "Generated by create next app",
  icons: './icon3.png'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className="w-full"
      >
        <NotificationProvider>
        
          {children}
         
          <SmoothScroll />
        
        </NotificationProvider>


      </body>
    </html>
  );
}
